// Карточки для тренировки. Привязаны к урокам через lessonId.
// Группа Светы: карточки добавляются сюда по мере готовности уроков
// (см. lessons.ts). Формат карточки:
// { id: 'l52-01', lessonId: 'lesson-52', vi: '...', ru: '...' }
// ID карточек должны быть постоянными после публикации.

import type { FlashCard } from '../types';

export const flashCards: FlashCard[] = [
  // Урок 42 — Магазины, еда и напитки.
  { id: 'l42-01', lessonId: 'lesson-42', vi: 'nhà hàng', ru: 'ресторан' },
  { id: 'l42-02', lessonId: 'lesson-42', vi: 'quán phở bò', ru: 'заведение / кафе с фо бо' },
  { id: 'l42-03', lessonId: 'lesson-42', vi: 'tiệm', ru: 'магазин / лавка' },
  { id: 'l42-04', lessonId: 'lesson-42', vi: 'cửa hàng', ru: 'магазин' },
  { id: 'l42-05', lessonId: 'lesson-42', vi: 'trung tâm thương mại', ru: 'торговый центр' },
  { id: 'l42-06', lessonId: 'lesson-42', vi: 'cho anh', ru: 'дайте мне' },
  { id: 'l42-07', lessonId: 'lesson-42', vi: 'đồ uống', ru: 'напитки' },
  { id: 'l42-08', lessonId: 'lesson-42', vi: 'bia', ru: 'пиво' },
  { id: 'l42-09', lessonId: 'lesson-42', vi: 'rượu', ru: 'алкоголь / спиртное' },
  { id: 'l42-10', lessonId: 'lesson-42', vi: 'rượu vang', ru: 'вино' },
  { id: 'l42-11', lessonId: 'lesson-42', vi: 'nước ngọt', ru: 'сладкий газированный напиток' },
  { id: 'l42-12', lessonId: 'lesson-42', vi: 'nước ép', ru: 'сок' },
  { id: 'l42-13', lessonId: 'lesson-42', vi: 'sinh tố', ru: 'смузи' },
  { id: 'l42-14', lessonId: 'lesson-42', vi: 'nước suối', ru: 'вода питьевая' },
  { id: 'l42-15', lessonId: 'lesson-42', vi: 'sữa', ru: 'молоко' },
  { id: 'l42-16', lessonId: 'lesson-42', vi: 'sữa bò', ru: 'коровье молоко' },
  { id: 'l42-17', lessonId: 'lesson-42', vi: 'sữa dê', ru: 'козье молоко' },
  { id: 'l42-18', lessonId: 'lesson-42', vi: 'trà', ru: 'чай' },
  { id: 'l42-19', lessonId: 'lesson-42', vi: 'cà phê', ru: 'кофе' },
  { id: 'l42-20', lessonId: 'lesson-42', vi: 'nước ga', ru: 'газированная вода' },
  { id: 'l42-21', lessonId: 'lesson-42', vi: 'lon', ru: 'жестяная банка' },
  { id: 'l42-22', lessonId: 'lesson-42', vi: 'túi', ru: 'пакет / сумка' },
  { id: 'l42-23', lessonId: 'lesson-42', vi: 'cốc nhựa', ru: 'пластиковый стакан' },
  { id: 'l42-24', lessonId: 'lesson-42', vi: 'bình giữ nhiệt', ru: 'термос' },
  { id: 'l42-25', lessonId: 'lesson-42', vi: 'cái này', ru: 'эта штука / это' },
  { id: 'l42-26', lessonId: 'lesson-42', vi: 'bữa ăn', ru: 'приём пищи' },
  { id: 'l42-27', lessonId: 'lesson-42', vi: 'canh', ru: 'бульон' },
  { id: 'l42-28', lessonId: 'lesson-42', vi: 'rau', ru: 'овощи' },
  { id: 'l42-29', lessonId: 'lesson-42', vi: 'cơm', ru: 'рис' },
  { id: 'l42-30', lessonId: 'lesson-42', vi: 'nước mắm', ru: 'рыбный соус' },
  { id: 'l42-31', lessonId: 'lesson-42', vi: 'phở', ru: 'лапша' },
  { id: 'l42-32', lessonId: 'lesson-42', vi: 'miến', ru: 'фунчоза' },
  { id: 'l42-33', lessonId: 'lesson-42', vi: 'bún', ru: 'круглая лапша' },
  { id: 'l42-34', lessonId: 'lesson-42', vi: 'mì', ru: 'яичная лапша' },
  { id: 'l42-35', lessonId: 'lesson-42', vi: 'tráng miệng', ru: 'десерт' },
  { id: 'l42-36', lessonId: 'lesson-42', vi: 'trái cây', ru: 'фрукты' },
  { id: 'l42-37', lessonId: 'lesson-42', vi: 'bánh ngọt', ru: 'булка / сладкая выпечка' },
  { id: 'l42-38', lessonId: 'lesson-42', vi: 'sữa chua', ru: 'йогурт' },
  { id: 'l42-39', lessonId: 'lesson-42', vi: 'sữa đặc', ru: 'сгущёнка' },
  { id: 'l42-40', lessonId: 'lesson-42', vi: 'kem', ru: 'мороженое' },
  { id: 'l42-41', lessonId: 'lesson-42', vi: 'sô cô la', ru: 'шоколад' },
  { id: 'l42-42', lessonId: 'lesson-42', vi: 'mật ong', ru: 'мёд' },
  { id: 'l42-43', lessonId: 'lesson-42', vi: 'phở bò', ru: 'фо бо' },
  { id: 'l42-44', lessonId: 'lesson-42', vi: 'bánh mì', ru: 'бань ми' },
  { id: 'l42-45', lessonId: 'lesson-42', vi: 'bánh bao', ru: 'баоцзы / паровая булочка' },
  { id: 'l42-46', lessonId: 'lesson-42', vi: 'cháo', ru: 'каша' },
  { id: 'l42-47', lessonId: 'lesson-42', vi: 'xôi', ru: 'липкий рис' },
  { id: 'l42-48', lessonId: 'lesson-42', vi: 'trứng', ru: 'яйцо' },

  // Урок 46 — Прилагательные: пары противоположностей и слова про вкус/
  // ощущения. Теории к этому уроку нет, только карточки.
  { id: 'l46-01', lessonId: 'lesson-46', vi: 'béo', ru: 'толстый' },
  { id: 'l46-02', lessonId: 'lesson-46', vi: 'gầy', ru: 'худой' },
  { id: 'l46-03', lessonId: 'lesson-46', vi: 'thấp', ru: 'низкий' },
  { id: 'l46-04', lessonId: 'lesson-46', vi: 'cao', ru: 'высокий' },
  { id: 'l46-05', lessonId: 'lesson-46', vi: 'to', ru: 'большой' },
  { id: 'l46-06', lessonId: 'lesson-46', vi: 'nhỏ', ru: 'маленький' },
  { id: 'l46-07', lessonId: 'lesson-46', vi: 'lớn', ru: 'взрослый' },
  { id: 'l46-08', lessonId: 'lesson-46', vi: 'trẻ', ru: 'молодой' },
  { id: 'l46-09', lessonId: 'lesson-46', vi: 'dày', ru: 'толстый (о предмете)' },
  { id: 'l46-10', lessonId: 'lesson-46', vi: 'mỏng', ru: 'тонкий' },
  { id: 'l46-11', lessonId: 'lesson-46', vi: 'đẹp', ru: 'красивый' },
  { id: 'l46-12', lessonId: 'lesson-46', vi: 'xấu', ru: 'некрасивый' },
  { id: 'l46-13', lessonId: 'lesson-46', vi: 'nóng', ru: 'горячий' },
  { id: 'l46-14', lessonId: 'lesson-46', vi: 'lạnh', ru: 'холодный' },
  { id: 'l46-15', lessonId: 'lesson-46', vi: 'dài', ru: 'длинный' },
  { id: 'l46-16', lessonId: 'lesson-46', vi: 'ngắn', ru: 'короткий' },
  { id: 'l46-17', lessonId: 'lesson-46', vi: 'yếu', ru: 'слабый' },
  { id: 'l46-18', lessonId: 'lesson-46', vi: 'khỏe', ru: 'здоровый / сильный' },
  { id: 'l46-19', lessonId: 'lesson-46', vi: 'giàu', ru: 'богатый' },
  { id: 'l46-20', lessonId: 'lesson-46', vi: 'nghèo', ru: 'бедный' },
  { id: 'l46-21', lessonId: 'lesson-46', vi: 'rộng', ru: 'просторный' },
  { id: 'l46-22', lessonId: 'lesson-46', vi: 'chật', ru: 'тесный' },
  { id: 'l46-23', lessonId: 'lesson-46', vi: 'đắt', ru: 'дорогой' },
  { id: 'l46-24', lessonId: 'lesson-46', vi: 'rẻ', ru: 'дешёвый' },
  { id: 'l46-25', lessonId: 'lesson-46', vi: 'bằng nhau', ru: 'равные / одинаковые' },
  { id: 'l46-26', lessonId: 'lesson-46', vi: 'giống nhau', ru: 'похожие / одинаковые' },
  { id: 'l46-27', lessonId: 'lesson-46', vi: 'nổi tiếng', ru: 'популярный / известный' },
  { id: 'l46-28', lessonId: 'lesson-46', vi: 'hay', ru: 'интересный / хороший' },
  { id: 'l46-29', lessonId: 'lesson-46', vi: 'cởi chuồng', ru: 'голый' },
  { id: 'l46-30', lessonId: 'lesson-46', vi: 'ngọt', ru: 'сладкий' },
  { id: 'l46-31', lessonId: 'lesson-46', vi: 'chua', ru: 'кислый' },
  { id: 'l46-32', lessonId: 'lesson-46', vi: 'đắng', ru: 'горький' },
  { id: 'l46-33', lessonId: 'lesson-46', vi: 'nhiều nước', ru: 'сочный' },
  { id: 'l46-34', lessonId: 'lesson-46', vi: 'chín', ru: 'спелый' },
  { id: 'l46-35', lessonId: 'lesson-46', vi: 'chát', ru: 'вяжущий' },
  { id: 'l46-36', lessonId: 'lesson-46', vi: 'bùi', ru: 'маслянистый / ореховый вкус' },
  { id: 'l46-37', lessonId: 'lesson-46', vi: 'cứng', ru: 'твёрдый' },
  { id: 'l46-38', lessonId: 'lesson-46', vi: 'mềm', ru: 'мягкий' },
  { id: 'l46-39', lessonId: 'lesson-46', vi: 'mặn', ru: 'солёный' },
  { id: 'l46-40', lessonId: 'lesson-46', vi: 'cay', ru: 'острый' },
  { id: 'l46-41', lessonId: 'lesson-46', vi: 'ổn', ru: 'нормальный / нормально' },
  { id: 'l46-42', lessonId: 'lesson-46', vi: 'khô', ru: 'сухой' },
  { id: 'l46-43', lessonId: 'lesson-46', vi: 'mát', ru: 'прохладный' },
  { id: 'l46-44', lessonId: 'lesson-46', vi: 'nắng', ru: 'солнечный' },
  { id: 'l46-45', lessonId: 'lesson-46', vi: 'ẩm', ru: 'влажный' },
  { id: 'l46-46', lessonId: 'lesson-46', vi: 'già', ru: 'старый' },

  // Урок 52 — So sánh (сравнение): слова на hơn/nhất/như/bằng, прилагательные
  // с противоположностями, несколько фраз из конспекта.
  { id: 'l52-01', lessonId: 'lesson-52', vi: 'hơn', ru: 'более / …-ее' },
  { id: 'l52-02', lessonId: 'lesson-52', vi: 'nhất', ru: 'самый / наиболее' },
  { id: 'l52-03', lessonId: 'lesson-52', vi: 'như', ru: 'как / такой же, как' },
  { id: 'l52-04', lessonId: 'lesson-52', vi: 'bằng', ru: 'такой же / равный по степени' },
  { id: 'l52-05', lessonId: 'lesson-52', vi: 'ngon hơn', ru: 'вкуснее' },
  { id: 'l52-06', lessonId: 'lesson-52', vi: 'cao hơn', ru: 'выше' },
  { id: 'l52-07', lessonId: 'lesson-52', vi: 'cao nhất', ru: 'самый высокий' },
  { id: 'l52-08', lessonId: 'lesson-52', vi: 'cao như', ru: 'высокий как / такой же высокий, как' },
  { id: 'l52-09', lessonId: 'lesson-52', vi: 'cao bằng', ru: 'такой же высокий / равный по росту' },
  { id: 'l52-10', lessonId: 'lesson-52', vi: 'Cà phê ngon hơn trà.', ru: 'Кофе вкуснее чая.' },
  {
    id: 'l52-11',
    lessonId: 'lesson-52',
    vi: 'Anh Sam cao như chị Sveta.',
    ru: 'Сэм такой же высокий, как Света.',
  },
  { id: 'l52-12', lessonId: 'lesson-52', vi: 'đắt', ru: 'дорогой' },
  { id: 'l52-13', lessonId: 'lesson-52', vi: 'rẻ', ru: 'дешёвый' },
  { id: 'l52-14', lessonId: 'lesson-52', vi: 'dài', ru: 'длинный' },
  { id: 'l52-15', lessonId: 'lesson-52', vi: 'ngắn', ru: 'короткий' },
  { id: 'l52-16', lessonId: 'lesson-52', vi: 'cao', ru: 'высокий' },
  { id: 'l52-17', lessonId: 'lesson-52', vi: 'thấp', ru: 'низкий' },
  { id: 'l52-18', lessonId: 'lesson-52', vi: 'đẹp', ru: 'красивый' },
  { id: 'l52-19', lessonId: 'lesson-52', vi: 'xấu', ru: 'некрасивый / плохой' },
  { id: 'l52-20', lessonId: 'lesson-52', vi: 'béo', ru: 'толстый (о человеке)' },
  { id: 'l52-21', lessonId: 'lesson-52', vi: 'gầy', ru: 'худой' },
  { id: 'l52-22', lessonId: 'lesson-52', vi: 'mới', ru: 'новый' },
  { id: 'l52-23', lessonId: 'lesson-52', vi: 'cũ', ru: 'старый (о предмете)' },
  { id: 'l52-24', lessonId: 'lesson-52', vi: 'trẻ', ru: 'молодой' },
  { id: 'l52-25', lessonId: 'lesson-52', vi: 'già', ru: 'старый / пожилой (о человеке)' },
  { id: 'l52-26', lessonId: 'lesson-52', vi: 'dày', ru: 'толстый (о предмете)' },
  { id: 'l52-27', lessonId: 'lesson-52', vi: 'mỏng', ru: 'тонкий' },
  { id: 'l52-28', lessonId: 'lesson-52', vi: 'thứ nhất', ru: 'первый' },
  { id: 'l52-29', lessonId: 'lesson-52', vi: 'thứ hai', ru: 'второй' },
  { id: 'l52-30', lessonId: 'lesson-52', vi: 'nói dối', ru: 'врать / говорить неправду' },
  { id: 'l52-31', lessonId: 'lesson-52', vi: 'Chị nói dối.', ru: 'Ты врёшь.' },
  { id: 'l52-32', lessonId: 'lesson-52', vi: 'sai', ru: 'ошибаться / быть неправым' },
  { id: 'l52-33', lessonId: 'lesson-52', vi: 'Chị đã sai.', ru: 'Ты ошиблась / была неправа.' },
  { id: 'l52-34', lessonId: 'lesson-52', vi: 'tốt', ru: 'хороший' },
  { id: 'l52-35', lessonId: 'lesson-52', vi: 'tốt nhất', ru: 'лучший / самый хороший' },
  {
    id: 'l52-36',
    lessonId: 'lesson-52',
    vi: 'Hôm nay là ngày tốt nhất.',
    ru: 'Сегодня лучший день.',
  },
];

export function getCardsForLesson(lessonId: string): FlashCard[] {
  return flashCards.filter((c) => c.lessonId === lessonId);
}
